# Generated by ariadne-codegen
# Source: ./graphpyshop/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BulkOperationErrorCode, BulkOperationStatus, BulkOperationType


class BulkOperationCancel(BaseModel):
    bulk_operation_cancel: Optional["BulkOperationCancelBulkOperationCancel"] = Field(
        alias="bulkOperationCancel"
    )


class BulkOperationCancelBulkOperationCancel(BaseModel):
    bulk_operation: Optional[
        "BulkOperationCancelBulkOperationCancelBulkOperation"
    ] = Field(alias="bulkOperation")
    user_errors: List["BulkOperationCancelBulkOperationCancelUserErrors"] = Field(
        alias="userErrors"
    )


class BulkOperationCancelBulkOperationCancelBulkOperation(BaseModel):
    id: str
    status: BulkOperationStatus
    type: BulkOperationType
    query: str
    error_code: Optional[BulkOperationErrorCode] = Field(alias="errorCode")
    object_count: Any = Field(alias="objectCount")
    root_object_count: Any = Field(alias="rootObjectCount")
    file_size: Optional[Any] = Field(alias="fileSize")
    url: Optional[Any]
    partial_data_url: Optional[Any] = Field(alias="partialDataUrl")
    created_at: Any = Field(alias="createdAt")
    completed_at: Optional[Any] = Field(alias="completedAt")


class BulkOperationCancelBulkOperationCancelUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


BulkOperationCancel.model_rebuild()
BulkOperationCancelBulkOperationCancel.model_rebuild()
