# Generated by ariadne-codegen
# Source: ./graphpyshop/queries

__all__ = [
    "BULK_OPERATION_CANCEL_GQL",
    "BULK_OPERATION_GQL",
    "BULK_OPERATION_RUN_MUTATION_GQL",
    "BULK_OPERATION_RUN_QUERY_GQL",
    "COLLECTIONS_GQL",
    "CURRENT_BULK_OPERATION_GQL",
    "CUSTOMERS_GQL",
    "ORDERS_GQL",
    "PRODUCTS_GQL",
    "PRODUCT_VARIANTS_GQL",
    "SUBSCRIPTION_BILLING_CYCLES_GQL",
    "SUBSCRIPTION_CONTRACTS_GQL",
    "WEBHOOK_SUBSCRIPTIONS_GQL",
    "WEBHOOK_SUBSCRIPTION_CREATE_GQL",
    "WEBHOOK_SUBSCRIPTION_DELETE_GQL",
    "WEBHOOK_SUBSCRIPTION_UPDATE_GQL",
]

BULK_OPERATION_GQL = """
query bulkOperation($id: ID!) {
  node(id: $id) {
    __typename
    ... on BulkOperation {
      id
      status
      errorCode
      createdAt
      completedAt
      objectCount
      rootObjectCount
      query
      url
      partialDataUrl
      fileSize
      type
    }
  }
}
"""

BULK_OPERATION_CANCEL_GQL = """
mutation bulkOperationCancel($id: ID!) {
  bulkOperationCancel(id: $id) {
    bulkOperation {
      id
      status
      type
      query
      errorCode
      objectCount
      rootObjectCount
      fileSize
      url
      partialDataUrl
      createdAt
      completedAt
    }
    userErrors {
      field
      message
    }
  }
}
"""

BULK_OPERATION_RUN_MUTATION_GQL = """
mutation bulkOperationRunMutation($mutation: String!, $stagedUploadPath: String!) {
  bulkOperationRunMutation(
    mutation: $mutation
    stagedUploadPath: $stagedUploadPath
  ) {
    bulkOperation {
      id
      status
      type
      query
      errorCode
      objectCount
      rootObjectCount
      fileSize
      url
      partialDataUrl
      createdAt
      completedAt
    }
    userErrors {
      field
      message
    }
  }
}
"""

BULK_OPERATION_RUN_QUERY_GQL = """
mutation bulkOperationRunQuery($query: String!) {
  bulkOperationRunQuery(query: $query) {
    bulkOperation {
      id
      status
      type
      query
      errorCode
      objectCount
      rootObjectCount
      fileSize
      url
      partialDataUrl
      createdAt
      completedAt
    }
    userErrors {
      field
      message
    }
  }
}
"""

COLLECTIONS_GQL = """
query collections($first: Int!, $query: String!) {
  collections(first: $first, query: $query) {
    edges {
      node {
        id
        description
        availablePublicationsCount {
          count
          precision
        }
        descriptionHtml
        feedback {
          summary
        }
        handle
        image {
          id
          altText
          height
          url
          width
        }
        publishedOnCurrentPublication
        resourcePublicationsCount {
          count
          precision
        }
        ruleSet {
          appliedDisjunctively
          rules {
            column
            condition
            relation
          }
        }
        seo {
          description
          title
        }
        sortOrder
        templateSuffix
        title
        updatedAt
      }
    }
  }
}
"""

CURRENT_BULK_OPERATION_GQL = """
query CurrentBulkOperation($type: BulkOperationType = QUERY) {
  currentBulkOperation(type: $type) {
    id
    type
    status
    completedAt
    createdAt
    errorCode
    fileSize
    objectCount
    partialDataUrl
    query
    rootObjectCount
    url
  }
}
"""

CUSTOMERS_GQL = """
query customers($first: Int!, $query: String!) {
  customers(first: $first, query: $query) {
    edges {
      node {
        id
        firstName
        lastName
        emailMarketingConsent {
          consentUpdatedAt
          marketingOptInLevel
          marketingState
        }
        smsMarketingConsent {
          consentCollectedFrom
          consentUpdatedAt
          marketingOptInLevel
          marketingState
        }
        state
        email
        phone
        amountSpent {
          amount
          currencyCode
        }
        createdAt
        updatedAt
        note
        verifiedEmail
        validEmailAddress
        tags
        lifetimeDuration
        productSubscriberStatus
        statistics {
          predictedSpendTier
        }
        defaultAddress {
          address1
          address2
          city
          company
          coordinatesValidated
          country
          countryCodeV2
          firstName
          formatted
          formattedArea
          id
          lastName
          latitude
          longitude
          name
          phone
          province
          provinceCode
          timeZone
          zip
        }
        addresses(first: 10) {
          address1
          address2
          city
          company
          coordinatesValidated
          country
          countryCodeV2
          firstName
          formatted
          formattedArea
          id
          lastName
          latitude
          longitude
          name
          phone
          province
          provinceCode
          timeZone
          zip
        }
        image {
          src
        }
        canDelete
      }
    }
  }
}
"""

ORDERS_GQL = """
query orders($first: Int!, $query: String!) {
  orders(first: $first, query: $query) {
    edges {
      node {
        id
        updatedAt
        name
        customer {
          id
        }
      }
    }
  }
}
"""

PRODUCT_VARIANTS_GQL = """
query productVariants($first: Int!, $query: String!) {
  productVariants(first: $first, query: $query) {
    edges {
      node {
        id
        updatedAt
      }
    }
  }
}
"""

PRODUCTS_GQL = """
query products($first: Int!, $query: String!) {
  products(first: $first, query: $query) {
    edges {
      node {
        id
        availablePublicationsCount {
          count
          precision
        }
        category {
          id
          ancestorIds
          childrenIds
          fullName
          isArchived
          isLeaf
          isRoot
          level
          name
          parentId
        }
        compareAtPriceRange {
          minVariantCompareAtPrice {
            amount
            currencyCode
          }
        }
        createdAt
        defaultCursor
        description
        descriptionHtml
        featuredImage {
          url
          width
          height
        }
        feedback {
          summary
        }
        giftCardTemplateSuffix
        handle
        hasOnlyDefaultVariant
        hasOutOfStockVariants
        hasVariantsThatRequiresComponents
        id
        isGiftCard
        legacyResourceId
        onlineStorePreviewUrl
        onlineStoreUrl
        options(first: 20) {
          id
          name
          optionValues {
            hasVariants
            id
            linkedMetafieldValue
            name
          }
          position
          values
        }
        priceRangeV2 {
          minVariantPrice {
            amount
            currencyCode
          }
        }
        productType
        publishedAt
        requiresSellingPlan
        sellingPlanGroupsCount {
          count
          precision
        }
        seo {
          description
          title
        }
        status
        tags
        templateSuffix
        title
        totalInventory
        tracksInventory
        updatedAt
        variantsCount {
          count
          precision
        }
        vendor
      }
    }
  }
}
"""

SUBSCRIPTION_BILLING_CYCLES_GQL = """
query subscriptionBillingCycles($first: Int!, $reverse: Boolean!, $contractId: ID!, $startDate: DateTime!, $endDate: DateTime!) {
  subscriptionBillingCycles(
    first: $first
    reverse: $reverse
    contractId: $contractId
    billingCyclesDateRangeSelector: {startDate: $startDate, endDate: $endDate}
  ) {
    edges {
      node {
        __typename
        billingAttemptExpectedDate
        cycleEndAt
        cycleIndex
        cycleStartAt
        edited
        editedContract {
          __typename
          app {
            id
          }
          appAdminUrl
          createdAt
          currencyCode
          customAttributes {
            key
            value
          }
          customer {
            id
          }
          customerPaymentMethod {
            id
          }
          deliveryPrice {
            amount
            currencyCode
          }
          linesCount {
            count
            precision
          }
          note
          price: priceBreakdownEstimate {
            subtotalPrice {
              amount
              currencyCode
            }
            taxesIncluded
            totalDiscounts {
              amount
              currencyCode
            }
            totalPrice {
              amount
              currencyCode
            }
            totalShippingPrice {
              amount
              currencyCode
            }
            totalTax {
              amount
              currencyCode
            }
          }
          lines(first: 20) {
            edges {
              node {
                __typename
                id
                currentPrice {
                  amount
                  currencyCode
                }
                customAttributes {
                  key
                  value
                }
                discountAllocations {
                  amount {
                    amount
                    currencyCode
                  }
                  discount {
                    __typename
                    ... on SubscriptionAppliedCodeDiscount {
                      id
                      redeemCode
                      rejectionReason
                    }
                    ... on SubscriptionManualDiscount {
                      entitledLines {
                        all
                      }
                      id
                      recurringCycleLimit
                      rejectionReason
                      targetType
                      title
                      type
                      usageCount
                      value {
                        __typename
                        ... on SubscriptionDiscountFixedAmountValue {
                          amount {
                            amount
                            currencyCode
                          }
                          appliesOnEachItem
                        }
                        ... on SubscriptionDiscountPercentageValue {
                          percentage
                        }
                      }
                    }
                  }
                }
                lineDiscountedPrice {
                  amount
                  currencyCode
                }
                pricingPolicy {
                  basePrice {
                    amount
                    currencyCode
                  }
                  cycleDiscounts {
                    adjustmentType
                    adjustmentValue {
                      __typename
                      ... on MoneyV2 {
                        amount
                        currencyCode
                      }
                      ... on SellingPlanPricingPolicyPercentageValue {
                        percentage
                      }
                    }
                    afterCycle
                    computedPrice {
                      amount
                      currencyCode
                    }
                  }
                }
                productId
                quantity
                requiresShipping
                sellingPlanId
                sellingPlanName
                sku
                taxable
                title
                variantId
                variantTitle
              }
            }
          }
          updatedAt
        }
        skipped
        sourceContract {
          id
        }
        status
      }
    }
  }
}
"""

SUBSCRIPTION_CONTRACTS_GQL = """
query subscriptionContracts($query: String!) {
  subscriptionContracts(query: $query) {
    edges {
      node {
        __typename
        id
        app {
          id
          handle
        }
        appAdminUrl
        billingPolicy {
          interval
          intervalCount
          anchors {
            day
            month
            type
            cutoffDay
          }
          maxCycles
          minCycles
        }
        createdAt
        currencyCode
        customAttributes {
          key
          value
        }
        customer {
          id
          displayName
          email
        }
        customerPaymentMethod {
          id
        }
        deliveryPolicy {
          interval
          intervalCount
          anchors {
            day
            month
            type
            cutoffDay
          }
        }
        deliveryPrice {
          amount
          currencyCode
        }
        id
        lastPaymentStatus
        linesCount {
          count
          precision
        }
        nextBillingDate
        note
        originOrder {
          id
          name
        }
        priceBreakdownEstimate {
          subtotalPrice {
            amount
            currencyCode
          }
          taxesIncluded
          totalDiscounts {
            amount
            currencyCode
          }
          totalPrice {
            amount
            currencyCode
          }
          totalShippingPrice {
            amount
            currencyCode
          }
          totalTax {
            amount
            currencyCode
          }
        }
        revisionId
        status
        updatedAt
        discounts(first: 10) {
          edges {
            node {
              __typename
              entitledLines {
                all
              }
              id
              recurringCycleLimit
              rejectionReason
              targetType
              title
              type
              usageCount
              value {
                __typename
                ... on SubscriptionDiscountFixedAmountValue {
                  amount {
                    amount
                    currencyCode
                  }
                  appliesOnEachItem
                }
                ... on SubscriptionDiscountPercentageValue {
                  percentage
                }
              }
            }
          }
        }
        lines(first: 10) {
          edges {
            node {
              __typename
              id
              currentPrice {
                amount
                currencyCode
              }
              customAttributes {
                key
                value
              }
              discountAllocations {
                amount {
                  amount
                  currencyCode
                }
                discount {
                  __typename
                  ... on SubscriptionAppliedCodeDiscount {
                    id
                    redeemCode
                    rejectionReason
                  }
                  ... on SubscriptionManualDiscount {
                    entitledLines {
                      all
                    }
                    id
                    recurringCycleLimit
                    rejectionReason
                    targetType
                    title
                    type
                    usageCount
                    value {
                      __typename
                      ... on SubscriptionDiscountFixedAmountValue {
                        amount {
                          amount
                          currencyCode
                        }
                        appliesOnEachItem
                      }
                      ... on SubscriptionDiscountPercentageValue {
                        percentage
                      }
                    }
                  }
                }
              }
              lineDiscountedPrice {
                amount
                currencyCode
              }
              pricingPolicy {
                basePrice {
                  amount
                  currencyCode
                }
                cycleDiscounts {
                  adjustmentType
                  adjustmentValue {
                    __typename
                    ... on MoneyV2 {
                      amount
                      currencyCode
                    }
                    ... on SellingPlanPricingPolicyPercentageValue {
                      percentage
                    }
                  }
                  afterCycle
                  computedPrice {
                    amount
                    currencyCode
                  }
                }
              }
              productId
              quantity
              requiresShipping
              sellingPlanId
              sellingPlanName
              sku
              taxable
              title
              variantId
              variantTitle
            }
          }
        }
      }
    }
  }
}
"""

WEBHOOK_SUBSCRIPTION_CREATE_GQL = """
mutation webhookSubscriptionCreate($topic: WebhookSubscriptionTopic!, $webhookSubscription: WebhookSubscriptionInput!) {
  webhookSubscriptionCreate(
    topic: $topic
    webhookSubscription: $webhookSubscription
  ) {
    webhookSubscription {
      id
      topic
      format
      createdAt
      updatedAt
      apiVersion {
        displayName
        handle
        supported
      }
      endpoint {
        __typename
        ... on WebhookHttpEndpoint {
          callbackUrl
        }
        ... on WebhookEventBridgeEndpoint {
          arn
        }
        ... on WebhookPubSubEndpoint {
          pubSubProject
          pubSubTopic
        }
      }
      includeFields
      legacyResourceId
      metafieldNamespaces
      subTopic
    }
    userErrors {
      field
      message
    }
  }
}
"""

WEBHOOK_SUBSCRIPTION_DELETE_GQL = """
mutation webhookSubscriptionDelete($id: ID!) {
  webhookSubscriptionDelete(id: $id) {
    userErrors {
      field
      message
    }
    deletedWebhookSubscriptionId
  }
}
"""

WEBHOOK_SUBSCRIPTION_UPDATE_GQL = """
mutation webhookSubscriptionUpdate($id: ID!, $webhookSubscription: WebhookSubscriptionInput!) {
  webhookSubscriptionUpdate(id: $id, webhookSubscription: $webhookSubscription) {
    webhookSubscription {
      id
      topic
      format
      createdAt
      updatedAt
      apiVersion {
        displayName
        handle
        supported
      }
      endpoint {
        __typename
        ... on WebhookHttpEndpoint {
          callbackUrl
        }
        ... on WebhookEventBridgeEndpoint {
          arn
        }
        ... on WebhookPubSubEndpoint {
          pubSubProject
          pubSubTopic
        }
      }
      includeFields
      legacyResourceId
      metafieldNamespaces
      subTopic
    }
    userErrors {
      field
      message
    }
  }
}
"""

WEBHOOK_SUBSCRIPTIONS_GQL = """
query webhookSubscriptions($first: Int!, $topics: [WebhookSubscriptionTopic!], $callbackUrl: URL!) {
  webhookSubscriptions(first: $first, topics: $topics, callbackUrl: $callbackUrl) {
    edges {
      node {
        __typename
        id
        topic
        endpoint {
          __typename
          ... on WebhookHttpEndpoint {
            callbackUrl
          }
          ... on WebhookEventBridgeEndpoint {
            arn
          }
          ... on WebhookPubSubEndpoint {
            pubSubProject
            pubSubTopic
          }
        }
      }
    }
  }
}
"""
