# Generated by ariadne-codegen
# Source: ./graphpyshop/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class Orders(BaseModel):
    orders: "OrdersOrders"


class OrdersOrders(BaseModel):
    edges: List["OrdersOrdersEdges"]


class OrdersOrdersEdges(BaseModel):
    node: "OrdersOrdersEdgesNode"


class OrdersOrdersEdgesNode(BaseModel):
    id: str
    updated_at: Any = Field(alias="updatedAt")
    name: str
    customer: Optional["OrdersOrdersEdgesNodeCustomer"]


class OrdersOrdersEdgesNodeCustomer(BaseModel):
    id: str


Orders.model_rebuild()
OrdersOrders.model_rebuild()
OrdersOrdersEdges.model_rebuild()
OrdersOrdersEdgesNode.model_rebuild()
