# Generated by ariadne-codegen
# Source: ./graphpyshop/queries

from typing import Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    CountPrecision,
    CurrencyCode,
    DiscountTargetType,
    DiscountType,
    SellingPlanPricingPolicyAdjustmentType,
    SubscriptionBillingCycleBillingCycleStatus,
    SubscriptionDiscountRejectionReason,
)


class SubscriptionBillingCycles(BaseModel):
    subscription_billing_cycles: "SubscriptionBillingCyclesSubscriptionBillingCycles" = Field(
        alias="subscriptionBillingCycles"
    )


class SubscriptionBillingCyclesSubscriptionBillingCycles(BaseModel):
    edges: List["SubscriptionBillingCyclesSubscriptionBillingCyclesEdges"]


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdges(BaseModel):
    node: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNode"


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNode(BaseModel):
    typename__: Literal["SubscriptionBillingCycle"] = Field(alias="__typename")
    billing_attempt_expected_date: Any = Field(alias="billingAttemptExpectedDate")
    cycle_end_at: Any = Field(alias="cycleEndAt")
    cycle_index: int = Field(alias="cycleIndex")
    cycle_start_at: Any = Field(alias="cycleStartAt")
    edited: bool
    edited_contract: Optional[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContract"
    ] = Field(alias="editedContract")
    skipped: bool
    source_contract: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeSourceContract" = Field(
        alias="sourceContract"
    )
    status: SubscriptionBillingCycleBillingCycleStatus


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContract(
    BaseModel
):
    typename__: Literal["SubscriptionBillingCycleEditedContract"] = Field(
        alias="__typename"
    )
    app: Optional[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractApp"
    ]
    app_admin_url: Optional[Any] = Field(alias="appAdminUrl")
    created_at: Any = Field(alias="createdAt")
    currency_code: CurrencyCode = Field(alias="currencyCode")
    custom_attributes: List[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractCustomAttributes"
    ] = Field(alias="customAttributes")
    customer: Optional[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractCustomer"
    ]
    customer_payment_method: Optional[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractCustomerPaymentMethod"
    ] = Field(alias="customerPaymentMethod")
    delivery_price: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractDeliveryPrice" = Field(
        alias="deliveryPrice"
    )
    lines_count: Optional[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesCount"
    ] = Field(alias="linesCount")
    note: Optional[str]
    price: Optional[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPrice"
    ]
    lines: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLines"
    updated_at: Any = Field(alias="updatedAt")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractApp(
    BaseModel
):
    id: str


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractCustomAttributes(
    BaseModel
):
    key: str
    value: Optional[str]


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractCustomer(
    BaseModel
):
    id: str


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractCustomerPaymentMethod(
    BaseModel
):
    id: str


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractDeliveryPrice(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesCount(
    BaseModel
):
    count: int
    precision: CountPrecision


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPrice(
    BaseModel
):
    subtotal_price: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceSubtotalPrice" = Field(
        alias="subtotalPrice"
    )
    taxes_included: bool = Field(alias="taxesIncluded")
    total_discounts: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceTotalDiscounts" = Field(
        alias="totalDiscounts"
    )
    total_price: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceTotalPrice" = Field(
        alias="totalPrice"
    )
    total_shipping_price: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceTotalShippingPrice" = Field(
        alias="totalShippingPrice"
    )
    total_tax: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceTotalTax" = Field(
        alias="totalTax"
    )


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceSubtotalPrice(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceTotalDiscounts(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceTotalPrice(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceTotalShippingPrice(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPriceTotalTax(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLines(
    BaseModel
):
    edges: List[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdges"
    ]


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdges(
    BaseModel
):
    node: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNode"


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNode(
    BaseModel
):
    typename__: Literal["SubscriptionLine"] = Field(alias="__typename")
    id: str
    current_price: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeCurrentPrice" = Field(
        alias="currentPrice"
    )
    custom_attributes: List[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeCustomAttributes"
    ] = Field(alias="customAttributes")
    discount_allocations: List[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocations"
    ] = Field(alias="discountAllocations")
    line_discounted_price: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeLineDiscountedPrice" = Field(
        alias="lineDiscountedPrice"
    )
    pricing_policy: Optional[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicy"
    ] = Field(alias="pricingPolicy")
    product_id: Optional[str] = Field(alias="productId")
    quantity: int
    requires_shipping: bool = Field(alias="requiresShipping")
    selling_plan_id: Optional[str] = Field(alias="sellingPlanId")
    selling_plan_name: Optional[str] = Field(alias="sellingPlanName")
    sku: Optional[str]
    taxable: bool
    title: str
    variant_id: Optional[str] = Field(alias="variantId")
    variant_title: Optional[str] = Field(alias="variantTitle")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeCurrentPrice(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeCustomAttributes(
    BaseModel
):
    key: str
    value: Optional[str]


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocations(
    BaseModel
):
    amount: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsAmount"
    discount: Union[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionAppliedCodeDiscount",
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscount",
    ] = Field(discriminator="typename__")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsAmount(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionAppliedCodeDiscount(
    BaseModel
):
    typename__: Literal["SubscriptionAppliedCodeDiscount"] = Field(alias="__typename")
    id: str
    redeem_code: str = Field(alias="redeemCode")
    rejection_reason: Optional[SubscriptionDiscountRejectionReason] = Field(
        alias="rejectionReason"
    )


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscount(
    BaseModel
):
    typename__: Literal["SubscriptionManualDiscount"] = Field(alias="__typename")
    entitled_lines: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscountEntitledLines" = Field(
        alias="entitledLines"
    )
    id: str
    recurring_cycle_limit: Optional[int] = Field(alias="recurringCycleLimit")
    rejection_reason: Optional[SubscriptionDiscountRejectionReason] = Field(
        alias="rejectionReason"
    )
    target_type: DiscountTargetType = Field(alias="targetType")
    title: Optional[str]
    type: DiscountType
    usage_count: int = Field(alias="usageCount")
    value: Union[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscountValueSubscriptionDiscountFixedAmountValue",
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscountValueSubscriptionDiscountPercentageValue",
    ] = Field(discriminator="typename__")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscountEntitledLines(
    BaseModel
):
    all: bool


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscountValueSubscriptionDiscountFixedAmountValue(
    BaseModel
):
    typename__: Literal["SubscriptionDiscountFixedAmountValue"] = Field(
        alias="__typename"
    )
    amount: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscountValueSubscriptionDiscountFixedAmountValueAmount"
    applies_on_each_item: bool = Field(alias="appliesOnEachItem")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscountValueSubscriptionDiscountFixedAmountValueAmount(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscountValueSubscriptionDiscountPercentageValue(
    BaseModel
):
    typename__: Literal["SubscriptionDiscountPercentageValue"] = Field(
        alias="__typename"
    )
    percentage: int


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeLineDiscountedPrice(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicy(
    BaseModel
):
    base_price: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyBasePrice" = Field(
        alias="basePrice"
    )
    cycle_discounts: List[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyCycleDiscounts"
    ] = Field(alias="cycleDiscounts")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyBasePrice(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyCycleDiscounts(
    BaseModel
):
    adjustment_type: SellingPlanPricingPolicyAdjustmentType = Field(
        alias="adjustmentType"
    )
    adjustment_value: Union[
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyCycleDiscountsAdjustmentValueMoneyV2",
        "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyCycleDiscountsAdjustmentValueSellingPlanPricingPolicyPercentageValue",
    ] = Field(alias="adjustmentValue", discriminator="typename__")
    after_cycle: int = Field(alias="afterCycle")
    computed_price: "SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyCycleDiscountsComputedPrice" = Field(
        alias="computedPrice"
    )


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyCycleDiscountsAdjustmentValueMoneyV2(
    BaseModel
):
    typename__: Literal["MoneyV2"] = Field(alias="__typename")
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyCycleDiscountsAdjustmentValueSellingPlanPricingPolicyPercentageValue(
    BaseModel
):
    typename__: Literal["SellingPlanPricingPolicyPercentageValue"] = Field(
        alias="__typename"
    )
    percentage: float


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyCycleDiscountsComputedPrice(
    BaseModel
):
    amount: Any
    currency_code: CurrencyCode = Field(alias="currencyCode")


class SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeSourceContract(
    BaseModel
):
    id: str


SubscriptionBillingCycles.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCycles.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdges.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNode.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContract.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractPrice.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLines.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdges.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNode.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocations.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscount.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodeDiscountAllocationsDiscountSubscriptionManualDiscountValueSubscriptionDiscountFixedAmountValue.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicy.model_rebuild()
SubscriptionBillingCyclesSubscriptionBillingCyclesEdgesNodeEditedContractLinesEdgesNodePricingPolicyCycleDiscounts.model_rebuild()
