# Generated by ariadne-codegen
# Source: ./graphpyshop/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class WebhookSubscriptionDelete(BaseModel):
    webhook_subscription_delete: Optional[
        "WebhookSubscriptionDeleteWebhookSubscriptionDelete"
    ] = Field(alias="webhookSubscriptionDelete")


class WebhookSubscriptionDeleteWebhookSubscriptionDelete(BaseModel):
    user_errors: List[
        "WebhookSubscriptionDeleteWebhookSubscriptionDeleteUserErrors"
    ] = Field(alias="userErrors")
    deleted_webhook_subscription_id: Optional[str] = Field(
        alias="deletedWebhookSubscriptionId"
    )


class WebhookSubscriptionDeleteWebhookSubscriptionDeleteUserErrors(BaseModel):
    field: Optional[List[str]]
    message: str


WebhookSubscriptionDelete.model_rebuild()
WebhookSubscriptionDeleteWebhookSubscriptionDelete.model_rebuild()
