# Generated by ariadne-codegen
# Source: ./graphpyshop/queries

from typing import Any, List, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import WebhookSubscriptionTopic


class WebhookSubscriptions(BaseModel):
    webhook_subscriptions: "WebhookSubscriptionsWebhookSubscriptions" = Field(
        alias="webhookSubscriptions"
    )


class WebhookSubscriptionsWebhookSubscriptions(BaseModel):
    edges: List["WebhookSubscriptionsWebhookSubscriptionsEdges"]


class WebhookSubscriptionsWebhookSubscriptionsEdges(BaseModel):
    node: "WebhookSubscriptionsWebhookSubscriptionsEdgesNode"


class WebhookSubscriptionsWebhookSubscriptionsEdgesNode(BaseModel):
    typename__: Literal["WebhookSubscription"] = Field(alias="__typename")
    id: str
    topic: WebhookSubscriptionTopic
    endpoint: Union[
        "WebhookSubscriptionsWebhookSubscriptionsEdgesNodeEndpointWebhookEventBridgeEndpoint",
        "WebhookSubscriptionsWebhookSubscriptionsEdgesNodeEndpointWebhookHttpEndpoint",
        "WebhookSubscriptionsWebhookSubscriptionsEdgesNodeEndpointWebhookPubSubEndpoint",
    ] = Field(discriminator="typename__")


class WebhookSubscriptionsWebhookSubscriptionsEdgesNodeEndpointWebhookEventBridgeEndpoint(
    BaseModel
):
    typename__: Literal["WebhookEventBridgeEndpoint"] = Field(alias="__typename")
    arn: Any


class WebhookSubscriptionsWebhookSubscriptionsEdgesNodeEndpointWebhookHttpEndpoint(
    BaseModel
):
    typename__: Literal["WebhookHttpEndpoint"] = Field(alias="__typename")
    callback_url: Any = Field(alias="callbackUrl")


class WebhookSubscriptionsWebhookSubscriptionsEdgesNodeEndpointWebhookPubSubEndpoint(
    BaseModel
):
    typename__: Literal["WebhookPubSubEndpoint"] = Field(alias="__typename")
    pub_sub_project: str = Field(alias="pubSubProject")
    pub_sub_topic: str = Field(alias="pubSubTopic")


WebhookSubscriptions.model_rebuild()
WebhookSubscriptionsWebhookSubscriptions.model_rebuild()
WebhookSubscriptionsWebhookSubscriptionsEdges.model_rebuild()
WebhookSubscriptionsWebhookSubscriptionsEdgesNode.model_rebuild()
