name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip twine build pip-tools
        python -m build
        pip install -e .
    
#    - name: Generate fresh client files
#      run: |
#        python -m graphpyshop generate
#
#    - name: Build package for distribution
#      run: |
#        python -m build
#
#    - name: Upload to PyPI
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_ACCESS_TOKEN }}
#      run: |
#        twine upload dist/*