name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip twine build pip-tools
        python -m build
        pip install -e .
    
    - name: Generate fresh client files
      env:
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        SHOPIFY_API_VERSION: unstable
        SHOPIFY_STORE: clean-kitchen-meal-kits
      run: |
        python -m graphpyshop generate-queries
        python -m graphpyshop generate-client

    - name: Build package for distribution
      run: |
        python -m build

#    - name: Upload to PyPI
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_ACCESS_TOKEN }}
#      run: |
#        twine upload dist/*